// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCet9axRopGWNUB2FqQw1Re2LRMgTKlbxU',
    appId: '1:467731991711:web:0ded6dade71011ffbda6aa',
    messagingSenderId: '467731991711',
    projectId: 'project-uas-mobile-d8f10',
    authDomain: 'project-uas-mobile-d8f10.firebaseapp.com',
    storageBucket: 'project-uas-mobile-d8f10.appspot.com',
    measurementId: 'G-3NBXV69LL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-EO7CI_cU_srJu9YgMWIXBS9qUP44X_g',
    appId: '1:467731991711:android:c5120db1dbac19bebda6aa',
    messagingSenderId: '467731991711',
    projectId: 'project-uas-mobile-d8f10',
    storageBucket: 'project-uas-mobile-d8f10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwRUJ44KQYPaBV6CivFUs_o_KXw3I5ohM',
    appId: '1:467731991711:ios:223ed4eee5507ac4bda6aa',
    messagingSenderId: '467731991711',
    projectId: 'project-uas-mobile-d8f10',
    storageBucket: 'project-uas-mobile-d8f10.appspot.com',
    iosBundleId: 'com.example.projectUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwRUJ44KQYPaBV6CivFUs_o_KXw3I5ohM',
    appId: '1:467731991711:ios:1bb3b7b0a32ad606bda6aa',
    messagingSenderId: '467731991711',
    projectId: 'project-uas-mobile-d8f10',
    storageBucket: 'project-uas-mobile-d8f10.appspot.com',
    iosBundleId: 'com.example.projectUas.RunnerTests',
  );
}
